### ISSUE TITLE
Update process doesn't work for Linux servers

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#224]
If Elexis is installed on a MySQL database on a Linux server (Mysql default install), then several update scripts for the database in `https://github.com/elexis/elexis-3-core/blob/master/ch.elexis.core.data/src/ch/elexis/core/data/util/DBUpdate.java` and 
`https://github.com/elexis/elexis-3-core/tree/master/ch.elexis.core.data/rsc/dbScripts` 
fail.

Reason: upper- and lowercase are used inconsistently.

Possible soulutions:

* Treat Elexis as "Windows only" (and probably macOS, on not case-sensitive file systems), or
* use upper- and lowercase consistently, or 
* convert all existing table names to lowercase and add a line "lower_case_table_names=1" to my.cnf.

**Comment by ngiger** [comment]
Hi Gerry,

I opt for solution 3 which can be done by each user and is documented.

Cleaning up would require a lot of work and quite impossible to make it correctly work for all possible update paths.

And the original code which causes the problem in question is over 10 years.

However patches to fix this problem would be highly welcome. And you certainly qualifiy a possible contributor to clean up this mess.

But I would suggest another alternative. Look at the available frameworks which allow clean migration of databases structures.

**Comment by rgwch** [comment]
Hi Niklaus

I just spent an hour to convert a customers' Database to lower case. There seems to be no easy way to bulk convert mysql table names. At least I didn't find any. Possibly the simplest solution would be a script. But obviously, there are not many users with Linux servers (I had always a Linux server, and it was not until Elexis version 3.x that I was hit by this problem). 

In the beginning, all Table names were strictly uppercase and so were all update scripts and access methods. Then some newer Plug-Ins didn't respect character case, but conversion was still simple, since all tables were myISAM - there you could just bulk rename the whole elexis database with a simple file rename. But with InnoDB, that's not an option anymore. So you must stick with mysql's `rename table ... to...`. Is there a method to bulk rename with this?
 
I would recommend to clearly announce "lower_case_table_names=1" as a requirement for new installations on mysql - it's much easier to start with an all-lowercase database than to convert later.

**Comment by ngiger** [comment]
Okay. I added the remarks about the my.cnf in

* https://wiki.elexis.info/Installation_Elexis_3.x_OpenSource
* https://wiki.elexis.info/Release-Notes-3.4.0

I learned a long time ago what you resumed by

>  - it's much easier to start with an all-lowercase database than to convert later.

**Comment by rgwch** [comment]
Thanks. One addition: In the release notes should be added, that it's necessary to rename existing tables manually to lowercase. The my.cnf entry `lower_case_tables_names=1` alone is NOT sufficient. It would even make a huge mess with many tables existing twice with different character cases.

So FIRST: Rename all tables to lowercase, SECOND: add the my.cnf entry, THIRD: restart server. FOURTH: Make the update.

**Comment by col-panic** [comment]
@ngiger what's the state on this issue?
