### ISSUE TITLE
jdbc driver fails on newer mysql versions

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#273]
Elexis target uses the jdbs driver 5..1.21. When connecting with mysql server 8.0.12, connection fails with a not too helpful error message: `java.sql.SQLException: java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long`.

Solution: use a newer JDBC driver. Versions after 5.1.45 are reported to work. When updating to the current driver 8.0.21, some more work is necessary: Include following lines to the mysql configuration file:

      useSSL=false
      default-time-zone="+01:00"

(or whatever suits)
Acceptable time zone expressions seem to be system dependent. Above ist correct with macOS. Others might need something like "UTC+1", "CEST"  or similar.

**Comment by rgwch** [comment]
Ist es eigentlich wirklich so schwierig, 5.1.46 ins target zu nehmen,  statt 5.1.21? Früher oder später werden auch Medelexis Kunden über das Problem stolpern, da der mysql-server in vielen setups automatisch upgedatet wird.

**Comment by ngiger** [comment]
Sorry, das habe ich übersehen. Medelexis hatte dies schon im August auf Version 3.8 eingeplant (https://redmine.medelexis.ch/issues/14376) aber keinem Entwickler zugeordnet. Ich hoffe, dass das noch auf 3.6 oder spätestens auf 3.7. Der Patch von mir dürfte nächste Woche im master Branch landen.

**Comment by col-panic** [comment]
With https://github.com/elexis/elexis-3-core/commit/f600e884fd2b98657b2fcd77e7d8f12d265283fc and https://github.com/elexis/elexis-3-core/commit/472115a702d81fba73ce5ccb25b5d9fc51428916 we update the mysql driver to 8.0.13.

First tests show the problem with default-time-zone; it is not acceptable to have to re-configure every db configuration, we have to find a solution for this.

**Comment by col-panic** [comment]
Ref: https://redmine.medelexis.ch/issues/14693

**Comment by col-panic** [comment]
We found out about the major issues, so this ticket should be closed.
