### ISSUE TITLE
DateTimeParseException exception in Konsultation#setDatum

### ISSUE THREAD

**Issue by d-roesch** [elexis/elexis-3-core#283]
I've seen that a couple of plugins are using the old version of setDatum with a string parameter that represents date and not date-time. I imagine that was the reason why following DateTimeFormatter was defined:

https://github.com/elexis/elexis-3-core/blob/caa36abb437583e9f543c33ec5496044e3832b2f/bundles/ch.elexis.core.data/src/ch/elexis/data/Konsultation.java#L68

The formatter is used to parse date strings to LocalDateTime:

https://github.com/elexis/elexis-3-core/blob/caa36abb437583e9f543c33ec5496044e3832b2f/bundles/ch.elexis.core.data/src/ch/elexis/data/Konsultation.java#L414-L415

But the use of this formatter results in an excpetion, because it parses a date and not to date-time string. The javadoc of LocalDateTime#parse states "_The string must represent a valid date-time..._" .

Maybe it would make sense to switch to LocalDate and mark the setDatum method as deprecated, because the usage setDateTime should be encouraged. If you agree, I can write a patch.

**Comment by col-panic** [comment]
@d-roesch I just recently implemented the "time extension" to the existing date element - thank you for finding this bug! Yes, please provide a patch for it!

**Comment by col-panic** [comment]
👍  @d-roesch - https://redmine.medelexis.ch/issues/4541
