### ISSUE TITLE
delete currently logged-in user

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#299]
In Datei-Einstellungen-Gruppen und Rechte-Benutzerverwaltung ist es ohne Weiteres möglich, den aktuell angemeldeten User zu löschen. Dann hat man sch erfolgreich ins Bein geschossen und kann Elexis nicht mehr verwenden.

Lösungsvorschlag: Das Löschen des momentan eingeloggten Anwenders sollte grundsätzlich nicht möglich sein.

**Comment by col-panic** [comment]
Should be solved with 73ec9f26f4db42a06026cbfd6da0af00a217a9c8

**Comment by rgwch** [comment]
passt
