### ISSUE TITLE
One more thing :)

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#36]
For me it worked only, after I changed the repository URLs:

* https://github.com/elexis/elexis-3-core.git
* https://github.com/elexis/elexis-3-base.git

That's probably because I use github via TLS (and not via SSH).

Then ch.elexis.core.data didn't compile, because it expects a different Guava version than included in the enviuronment. (I know, it's not possible to catch up with all changes in all subprojects continuously, but.. only.. just to start with a working thing ;))

and finally, ch.elexis.agenda doesn't compile because it expects some `edu.emory.mathcs.backport;bundle-version="3.1.0"? which is not included. 

And the run configuration doesn't work anymore: 

eclipse.buildId=unknown
java.version=1.7.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -product ch.elexis.core.application.product
Command-line arguments:  -product ch.elexis.core.application.product -data /Users/gerry/Documents/development/oomph/elexis-master/ws/../runtime-Elexis.product -dev file:/Users/gerry/Documents/development/oomph/elexis-master/ws/.metadata/.plugins/org.eclipse.pde.core/ElexisCore (OS X)/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -console

org.eclipse.osgi
Error
Wed May 20 17:04:51 CEST 2015
Could not find bundle: org.eclipse.equinox.console

org.osgi.framework.BundleException: Could not find bundle: org.eclipse.equinox.console
	at org.eclipse.osgi.framework.internal.core.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:211)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:297)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by rgwch** [comment]
I'm not able to resolve the issue. After some editing and recompiling, the following error persist:

Bundle reference:file:/Users/gerry/Documents/development/oomph/elexis-master/git/elexis-3-core/ch.elexis.core.data/ was not resolved.
Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.8))".

Probably, I should chose Eclipse JEE instead of RCP/RAP in the first place after oomph-start?

**Comment by col-panic** [comment]
hy gerry, we are currently in the process of migrating to java 8, the setup will be fixed once the migration is finished!

please be patient 😃

Von meinem iPhone gesendet

**Comment by rgwch** [comment]
Patience!?! Here?  What kind of sorcery would that be??

**Comment by col-panic** [comment]
The current state:
* After set-up currently the wrong target file is initialized, this is due to 2 juno-target.target files being available (one in .release), we will have to change this. After setting the correct target (in ch.elexis.core.target/juno-target.target) you should not face any additional problems. I will follow up on that.
* the new structure requires Java 8, as Java 7 has been declared end of life you are now required to have at least Java8 (-> missing required capability).
* when it comes to the repo urls, on setup Ooomph asks you what access type you want to use, so this is not something we may change on our site but which is a user selection

:)

**Comment by rgwch** [comment]
I tried this today with a new build from scratch (MacOSX 10.10.3). 
(For the records: it's *ch.elexis.target*/juno-target.target.)

After setting the target, it compiles ok. Run fails: I had to change the execution environment in the run configuration to Java 8. After that, it worked :)

Great Job, Thank you!
