### ISSUE TITLE
move elexis/elexis-3-core to elexis/elexis-3-core-old and move ngiger/elexis-3-core to elexis/elexis-3-core

### ISSUE THREAD

**Issue by Neustradamus** [elexis/elexis-3-core#371]
Can you move elexis/elexis-3-core to elexis/elexis-3-core-old and move ngiger/elexis-3-core to elexis/elexis-3-core?

It is not logic to have a fork ;)

**Comment by col-panic** [comment]
there is always logic in having a fork!

https://m.youtube.com/watch?v=HDZs0S7qd64

best marco

Von meinem iPhone gesendet

**Comment by Neustradamus** [comment]
Better to have:
- Org: main repository

@ngiger @col-panic @huthomas : https://help.github.com/articles/about-repository-transfers/

**Comment by col-panic** [comment]
sorry, but why are you even interested in this „problem“? 

thx marco

**Comment by Neustradamus** [comment]
It is a beautiful remark, if no people informs, never changes ;)
Easy to do it, in few minutes and no lost in the process!

**Comment by col-panic** [comment]
@ngiger sollen wir uns das ansehen?

**Comment by col-panic** [comment]
Fixed by ngiger removing his fork.
