### ISSUE TITLE
Why Java 7u55?

### ISSUE THREAD

**Issue by keilw** [elexis/elexis-3-core#40]
At least the Readme states:
"Install Oracle java 1.7.55". That's a rather antiquated and potentially security-flawed version. Especially doctors who care about privacy and their patient's data probably don't want to take a risk here, so ideally if Java 7 is required, why not use the last version, Oracle provides so far?

**Comment by ngiger** [comment]
Thanks for pointing to it. The readme has simply not been updated for a while. 
For the master branch we need in any case Java8 and for the release branch we use the latest 1.7 branch.
It should work with OpenJDK and Oracle.

I will have a look at the readme and update it accordingly.

**Comment by ngiger** [comment]
Fixed with commit https://github.com/elexis/elexis-3-core/commit/5390320a251cc5441ec8ebd9a0e961b1e988757e
