### ISSUE TITLE
Artikelstamm Änderung

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#400]
Ist die letzte Änderung am Artikelstamm-Format eigentlich irgendwo dokumentiert (Chapter70_HACK) ?

**Comment by col-panic** [comment]
Ich hab da schon länger keinen Einblick mehr -  @ngiger bitte um Feedback :) !

**Comment by ngiger** [comment]
Das ist dokumentiert im oddb2xml.

* https://github.com/zdavatz/oddb2xml/commit/8488177a324d1ca89544787341e45a4e290aca7e
* https://github.com/zdavatz/oddb2xml/commit/90d0dac34ddcb322b45c06795dc6716b021a0f22

Das XSD vom Arrtikelstamm dazu findet man unter https://github.com/zdavatz/oddb2xml/blob/master/Elexis_Artikelstamm_v5.xsd

Im https://github.com/zdavatz/oddb2xml/blob/master/History.txt#L14 findet man auch einen (vielleicht zu kurzen) Hinweis dazu

Die Generation des Artiktelstamm ist nicht Teil vom elexis! Das wird im Ruby Gem oddb2xml erledigt.
Der Chapter 70 Hack ist ein Hack, damit gewisse Produkte wie Urtinkturen aus der Komplementärmedizin als Medis erkannt werden.

@rgwch: Falls Du aus Deiner Sicht einen Vorschlag hast, wie ich das besser dokumentieren soll, mach bitte einen Vorschlag.

**Comment by rgwch** [comment]
Wenn etwas nicht mehr geht wie vorher, ist das eine kompatibilitätsbrechende Änderung, die eigentlich einen Versionssprung und einen Eintrag in einem Change log rechtfertigen würde. Ich sehe ein, dass die Abhängigkeit von Dritten, die ihre Datenformate jederzeit ändern können, ein grundlegenderes Problem ist. Aber in dem Moment, wo man das Problem in Elexis behoben hat, hätte man das ja auch kurz hier oder in der Mailingliste mitteilen können. OpenSource hat m.E. auch mit Kommunikation zu tun.

**Comment by rgwch** [comment]
Also ich mache Folgendes:
* Lade Elexis 3.6 herunter von https://download.elexis.info/elexis/3.6/products/, Version Linux GTK 64
* Führe Elexis aus und installiere Elexis Swiss OpenSource Feature von ch.elexis.base.p2site - https://download.elexis.info/elexis/3.6/p2/elexis-3-base
* Lade Artikelstamm herunter: https://artikelstamm.elexis.info/v5/20201001/artikelstamm_01102020_v5.xml
* Versuche diesen Artikelstamm einzulesen.

Resultat:

````
Fehler beim Einlesen der Import-Datei
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 171; columnNumber: 54; Zeichenfolge "--" ist in Kommentaren nicht zulässig.]
````
Passiert das wirklich nur bei mir? Was mache ich falsch?

**Comment by tecalto** [comment]
Ich meine, dass ist kein Problem vom Elexis, sondern vom xml-File. Irgendwie haben sich da `--` in die Kommentare verirrt, was gemäss [https://www.w3.org/TR/REC-xml/#sec-comments](www.w3.org) nicht sein sollte:

>  For compatibility, the string " -- " (double-hyphen) must not occur within comments.

**Comment by rgwch** [comment]
Gut möglich. Darum meine Eingangsfrage, ob und wie die Änderung am Artikelstamm-Format dokumentiert ist. Was mich aber verblüfft ist, dass es offenbar nicht wirklich aufgefallen ist und seit dem 24.8. auch niemanden wirklich interessiert hat.  In allen SD-Kantonen werden die Anwender doch den Artikelstamm hin und wieder updaten. Darum: Mache ich etwas falsch, oder liest wirklich niemand sonst den Artikelstamm ein, so dass die Auswirkung der Formatänderung niemandem aufgefallen ist?

**Comment by madElexis** [comment]
@rgwch passiert nicht nur bei Dir. Für das aktuelle Update habe ich das XML manuell angepasst. Erhalte beim Import vom Original-Build von @ngiger auf Jenkins folgende Fehlermeldungen:

Caused by: org.xml.sax.SAXParseException: Zeichenfolge "--" ist in Kommentaren nicht zulässig.

Als Beispiel dazu aus dem XML (liegt am "--" im Schnippsel 1--9):
<PRODUCT>
            <PRODNO>2069645</PRODNO>
            
            <SALECD>A</SALECD>
            <DSCR>D/C 1--9</DSCR>
            <DSCRF/>
 </PRODUCT>

Sobald das alles stimmt kommt die nächste Exception. Wurde anscheinend nicht geloggt, in der Konsole aber ersichtlich -> muss es nochmal durchspielen. Melde mich dann nochmal sobald ich die Exception habe.

**Comment by ngiger** [comment]
Sorry für den Fehler! Auf dem BuildServer war irgendwie die xmllint Applikation nicht mehr drin und dann wurde beim Erstellen des Artikelstamms xmllint nicht mehr aufgerufen. Habe den Fehler mit '--' lokal geflickt. Muss jedoch noch testen, ob das reicht, damit keine Fehler mehr auftreten und die Builds gehen jeweils 1 bis 2h

**Comment by madElexis** [comment]
Konnte den Fehler mit den fehlenden <SALECD> nicht mehr reproduzieren. @ngiger Hast Du da schon etwas gemacht?

**Comment by ngiger** [comment]
S.a: https://github.com/zdavatz/oddb2xml/issues/44
Habe https://github.com/ngiger/oddb2xml/commit/276ab08cbe83d5e481561915da37819d861cf935 gepushed. Problem sollte damit gefixt sein. 
Der Build https://srv.elexis.info/jenkins/view/Artikelstamm/job/Artikelstamm_oddb2xml_v5/149/ ist am Laufen und sollte in ca. 2h durch sein.

**Comment by rgwch** [comment]
Jetzt funktioniert es bei mir auch wieder, (mit 09102020_v5.xml). Vielen Dank!
