### ISSUE TITLE
NoSuchMethodException: ch.elexis.data.Patient.getAusstand Triamed()

### ISSUE THREAD

**Issue by danielludin** [elexis/elexis-3-core#41]
dies ist nur ein Beispiel, es gibt weitere fehlende Properties in dieser Entity. Die
Methodenaufrufe werden automatisch in der Patient Detail View durch die Eingabefelder
generiert.

**Comment by ngiger** [comment]
Wurde hier mal ein Import von Triamed-Daten vor x Jahren durchgeführt und das Triamed-Import-Plugin ist nicht geladen?

**Comment by danielludin** [comment]
Habe die Auskunft bekommen, dass das tatsächlich so ist.
