### ISSUE TITLE
elexis repos < 3.7 not available anymore

### ISSUE THREAD

**Issue by fschmid** [elexis/elexis-3-core#416]
P2 Repos < 3.7 are not available anymore (for example http://download.elexis.info/elexis/3.6/p2/target/). Please reactivate if possible from 3.1 onwards.

**Comment by col-panic** [comment]
We are currently in the progress of transitioning the download artifacts. We decided to only keep the p2 branches for maintained releases. Releases < 3.7 are not maintained anymore and should not be installed, resp. they do not provide any updates. What is your specific use-case?

**Comment by fschmid** [comment]
we are still running on 3.1 and are updating to 3.6. (Never got 3.7 or 3.8 compiling in Eclipse Linux 64bit  and according to release notes https://wiki.elexis.info/Release-Notes-3.8.0 3.8 is not released yet and 3.7 https://wiki.elexis.info/Release-Notes-3.7.0 has issues with Hilotec Open Document Plugin which we use)

**Comment by fschmid** [comment]
bump

**Comment by col-panic** [comment]
Please have a look at http://archive.elexis.info/elexis/ in the meantime and copy the required artifacts. We are not sure on how long this repo will stay available!

**Comment by ngiger** [comment]
Re-restored https://archive.elexis.info/elexis/3.7/

But please update to 3.9 or master in a month or too. Archive.download.elexis.info will go away ...
