### ISSUE TITLE
Weiterer Fehler beim HL7-Import

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#45]
Der Importer  scheint auch bekannte Laborparameter als unbekannt zu betrachten :(

Nach dem Import erhält man neue automatisch erstellte Laborgruppen mit neuen Items, auch wenn diese Laborparameter früher schon erstellt wurden. (Z Automatisch_01.07.2016 und Z_Automatisch_06.07.2016 wurden eben aus einem Import von einer einzelnen BE mit Nachtragsbefund erstellt)

![labor_1](https://cloud.githubusercontent.com/assets/3314994/16613717/d19f10f4-436d-11e6-9cb6-ad0ec1ef9491.png)

Dabei wären dieselben Parameter schon in anderen Gruppen vorhanden gewesen, z.B. hier:
![labor_2](https://cloud.githubusercontent.com/assets/3314994/16613743/e8ebb384-436d-11e6-9834-9dd88d76611f.png)

Wurde die Erkennung vorhandener Laboratems verändert? Oder die policy, wann neue Items erstellt werden?

**Comment by col-panic** [comment]
Wir hatten für 3.2 einige große Umbauten, vor allem auch in Richtung LabImport Util. Das Ziel ist den HL7 Importer auch auf dem Server lauffähig zu machen. Diese Umbauten sind noch nicht abgeschlossen, unsere Tests bzgl. Import zeigen jedoch keine Fehler an. 

Kannst du uns Testdaten zu diesem Fehler zukommen lassen? Also am besten die entspr. HL7 files und die definierten LaborItems?!

Danke!

**Comment by col-panic** [comment]
Fehler könnte durch https://github.com/elexis/elexis-3-core/commit/1a2f95c898e49bf2ba09149beadf51f7c233ef03 gelöst worden sein!

**Comment by rgwch** [comment]
Leider nein:
![labor_2016-07-08](https://cloud.githubusercontent.com/assets/3314994/16684157/d7c0114e-4503-11e6-8278-c837ab75fb44.png)
Siehe die Blutentnahme vom 5.7.16: Am 1.7. war bereits beim Import von einem anderen Patienten die neue Gruppe "Automatisch_1.7.2016" erstellt worden. Das B12 wurde zu diesem Item gerechnet (obwohl derselbe Parameter in "Vitamine und Spurenelemente" schon vorhanden gewesen wäre). 
Das Vitamin D wurde dann zu einer neuen Gruppe "Automatisch_8.7.2016" erstellt, obwohl auch dieses Item bereits existieren würde. Hier wurde als besondere Erschwernis auch nicht mal ein Referenzbereich eingetragen.

Also: Es scheint irgendeinen neuen Importer zu geben, welcher die alten Items nicht erkennt. Hingegen scheint er seine eigenen Items zu erkennen (Das B12-Item vom 1.7.16 wurde am 5.7. wieder verwendet). Ich gehe davon aus, dass die Identifikation der Items irgendwie geändert wurde und jetzt zwar wieder in sich konsistent, aber inkompatibel zu früher ist.
Habe im Moment aber keine Zeit für längere Studien, vielleicht am Wochenende.

**Comment by rgwch** [comment]
Ich muss mich entschuldigen, war mein Fehler. Da mein labor-Importer Medelexis-proprietär war, und ich nur freie Plugins verwenden wollte, habe ich den "Rischbern" importer verwendet. Da dieser einen anderen Identifikationsstring verwendet, "meint" der Importer spezifikationsgemäss korrekt, dass das "Rischbern" Item nicht dasselbe Item ist, wie bei früheren Importen von "Risch". 
Ich musste also nur einen neuen Laborimporter für Risch machen, was trivial ist:
[https://github.com/rgwch/elexis-3-base/tree/master/ch.elexis.laborimport_risch](https://github.com/rgwch/elexis-3-base/tree/master/ch.elexis.laborimport_risch)

Darf selbstverständlich gern auch ins elexis-Repository übernommen werden, wenn gewünscht.
