### ISSUE TITLE
demodb on Windows fails on startup

### ISSUE THREAD

**Issue by jntme** [elexis/elexis-3-core#52]
I started the ElexisCore and got the following:

```
10:28:35.445 [main] INFO  ch.elexis.data.PersistentObject - Starting migration to new user structure
10:28:35.448 [main] DEBUG ch.elexis.data.Query - Executed SELECT ID FROM KONTAKT WHERE istAnwender='1' AND deleted='0'
10:28:35.461 [main] WARN  ch.elexis.data.PersistentObject - Password for Anwender mpa is empty, setting 'pass' and deactivating user.
```

[elexis_error.txt](https://github.com/elexis/elexis-3-core/files/787062/elexis_error.txt)

**Comment by col-panic** [comment]
Thanks for the info! Should be fixed with the newest build. Please try again!

**Comment by ngiger** [comment]
Fixed for me with commit https://github.com/elexis/elexis-3-core/commit/6cda14c671ba29178d806ee7502cb31dceb3c792

**Comment by jntme** [comment]
thx - everything ran through. 👍
