### ISSUE TITLE
Elexis not starting

### ISSUE THREAD

**Issue by gortmanns** [elexis/elexis-3-core#656]
After failing to install Elexis-OOB (different topic, feel free to ask about my experience how and why this did not work) I tried to install Elexis Classic on Ubuntu Server 22.04.4 with a Windows 10 Professional client.
After overcoming some minor issues due to changes how newer mySQL database versions handle some commands, I finally manged to get everything going - at least that was what I thought then..

Database existed (empty) and then I started the previously downloaded und unzipped Elexis3.exe on my windows client.
Up came the screen where I was prompted to enter the information  how to connect to the database. Did that and the programm populated the databse with some tables (confirmed that on the server) and closed itself.
Then I ran Elexis3,exe again on my windows machine and there was a screen to enter the personal information of the first doctor to use the system. Did that and then..... it closed again and .... nothing.

In the log file that was created in the folder 

`<Elexis-Install Path>\workspace\.metadata`

I found this entry:

`!ENTRY ch.elexis.core.logging.osgi 4 0 2024-04-07 22:54:57.426
!MESSAGE Component descriptor entry 'OSGI-INF/ch.elexis.core.logging.osgi.OsgiSl4fjLoggingAdapter.xml' not found

!ENTRY ch.elexis.core.data 2 2 2024-04-07 22:55:00.172
!MESSAGE Fataler Fehler bei Datenbank-Update: Kann keine Versionsinformation lesen. Abbruch`

When I try to start Elexis3.exe, nothing happens, except that more of the above error messages get written into the log file.

How can I fix this and actually start using Elexis?

**Comment by gortmanns** [comment]
I just followed all the steps in the guide from elexis.ch.

Unfortunately the docker Image install of elexis-oob did not work. First the maven dependency was broken. I was able to fix this (see my comment on the issue in the elexis-oob project) but then it appears the elexis inside the contaier could not resolve DNS requests. After a lot of Google search it seems that between docker version 16 and 17 the default behaviour of networking somehow changed and I was not able to find a solution to fix that issue.

So I tried to build elexis core instead of the docker image on an ubuntu server 22.04.
On the Linux side of things everything worked pretty well. Just 3 minor issues;
1. Current Java version is 11 not 8 on that release. So I had to downgrade manually to version 8. Not a big deal.
2. MySQL server in version 8 has changed default to sha2 passwords. So I had to change this manually in the config file to use the plain passwords used before. Again, not a big deal.
3. I had to allow mysql requests to go through the firewall.  Again easy fix.

So the Linux side of things is set up perfectly now.
Then I just downloaded the provided zip archive for my Windows 11 Client and got the issue described before and don't know how to fix this.
________________________________

**Comment by col-panic** [comment]
I'm confused. Which guide did you follow? Elexis-OOB is a completely different project. Can't give you information about this. Are you using elexis-server? I am sorry, but your issues seems to have nothing to do with this repository.

**Comment by gortmanns** [comment]
I first tried elexis-oob because on the website elexis.ch,  that was suggested as the most simple way.
But when I ran into multiple issues and finally one I could not resolve, I changed my approach.

I then decided to try Elexis Classic (that is what it is called on the website at least) where I had to clone all the github sources and compile the elexis serrver myself. I did all that and after resolving the issues I described before, the final step should habe been to just download the elexis client package for my system (Windows 11) and run it.
And that is when the error came up for which I am not able to find a solution.
________________________________

**Comment by col-panic** [comment]
What are you actually trying to achieve? Do you want to run the elexis-server or the Elexis RCP application? 
You can download the current stable Elexis Open-Source from http://download.elexis.info/elexis/3.10/products/

The problem you described may occur on elexis-server, so if you want to run this, I advise you to run it via https://github.com/elexis/elexis-server?tab=readme-ov-file#running-via-docker

**Comment by col-panic** [comment]
Please re-open if required.
