### ISSUE TITLE
Display flaws when using Ubuntu Linux/GTK

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-core#699]
This applies to (at least) Ubuntu 23.10 and 24.04 with Gnome Desktop. I tried with X11 and with Wayland Subsystem, no difference.
It does not concern my Laptop with Tuxedo Linux 2.0 and KDE Desktop. So it's probably related to gnome/GTK.

**Description**:

1. Drop down menus are transparent, so it's difficult to use them if somethings on the background: ![grafik](https://github.com/user-attachments/assets/01f0b58d-474c-4264-b4ee-0c446a1284db)
2. Height of dialog boxes is not calculated correctly for initial display:  ![grafik](https://github.com/user-attachments/assets/91e7e0cf-2a10-403a-91d1-0dbc0307639c).
If the dialog box is resizeable, it is possible to drag the bottom border and display it completely:  ![grafik](https://github.com/user-attachments/assets/feafd41a-971c-439a-8684-4d6c4b2ec05c)

**Comment by huthomas** [comment]
This seems to be a problem with the css.

**Comment by huthomas** [comment]
As I am not able to find the parts in the css causing the problem, the css has been removed from the product definition.

If there is the need to have a styled UI maybe one of the eclipse platform css should be used. Those are located here.
https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.themes/css

**Comment by rgwch** [comment]
Didn't change anything...

**Comment by huthomas** [comment]
Also removed the css file from the extension of the core application bundle.

**Comment by col-panic** [comment]
Maybe we need a newer SWT library. I have a problem with OS X in the IDE where suddenly all buttons vanish, and other weird problems! I updated (in my IDE only) to a newer SWT version and everything works ok.

Funny thing is, it is not aproblem on the built product!

**Comment by rgwch** [comment]
- Pulled elexis-3-core and elexis-3-base
- Cleaned all projects, rebuild
- Cleaned Workspace and configuration area
- launched product

Result:
![image](https://github.com/user-attachments/assets/42847c4b-3a54-430b-86af-a077318905e1)

So, probably it's not the css after all....

**Comment by col-panic** [comment]
@rgwch are you trying master? Does it occur on the productive build (not in the IDE)? See https://download.elexis.info/elexis/master/products/ e.g. for the Open Source `master` build. There are product builds for every branch.

**Comment by rgwch** [comment]
Ehm no, there are no products for 3.12. That's why I had to setup my own jenkins when starting with this ;-)

But.. Yesss! Problem gone with master:
![image](https://github.com/user-attachments/assets/0e2a941b-cf5d-48d3-be86-1af56b0e9a48)

Can you backport the solution? ;-)

**Comment by huthomas** [comment]
I had reproduced the problem with the master branch, starting Elexis from the IDE. After removing the CSS from all occurrences the Problem is fixed.

Thx for verifying the solution. I will backport the change to 3.12.

**Comment by col-panic** [comment]
> Ehm no, there are no products for 3.12. That's why I had to setup my own jenkins when starting with this ;-)
> 
> Can you backport the solution? ;-)
> 
> (For 3.12 there was no difference between product and IDE. For master I tested IDE only)

Oh I see, sorry we missed that, they are now available https://download.elexis.info/elexis/3.12/products/

I can't backport anything :) Please check if 3.12 works for you as product download. Maybe its a problem which happens only in the IDE.

**Comment by rgwch** [comment]
> I reproduced the problem with the master branch, starting Elexis from the IDE. After removing the CSS from all occurrences, the problem is fixed.
> 
> Thx for verifying the solution. I will backport the change to 3.12.

It works now in 3.12. Thanks!
