### ISSUE TITLE
Problems after installing ruby plugin

### ISSUE THREAD

**Issue by col-panic** [elexis/elexis-3-core#71]
After installing the ruby plugin, several errors pop-up. First we have a build error when cleaning the projects. Then there is a project error itself. Please see then enclosed screenshot.
![2017-04-18_0811](https://cloud.githubusercontent.com/assets/1679857/25116703/b5a00656-240e-11e7-943f-5666e0a2c940.png)

**Comment by col-panic** [comment]
New Problem

![image](https://cloud.githubusercontent.com/assets/1679857/26392306/6b115d1e-4066-11e7-96b5-28fb5a561c22.png)

**Comment by col-panic** [comment]
@ngiger könntest du das bitte kurz korrigieren? Das wäre sehr toll, danke!

**Comment by ngiger** [comment]
Fixed with 65003b0bf78d404333378da56a5c3da5f03abd2b
Therefore closing.
